const katalogKelas = [
  {
    name: 'Belajar HTML & CSS',
    photo: '/src/assets/images/kelas/htmlcss.webp',
    price: 'Rp 350.000',
    rating: '4.7',
    students: '6.204',
  },
  {
    name: 'Belajar Javascript',
    photo: '/src/assets/images/kelas/javascript.webp',
    price: 'Rp 500.000',
    rating: '4.8',
    students: '7.295',
  },
  {
    name: 'Belajar Flutter',
    photo: '/src/assets/images/kelas/flutter.webp',
    price: 'Rp 450.000',
    rating: '4.6',
    students: '3.125',
  },
  {
    name: 'Belajar Express JS',
    photo: '/src/assets/images/kelas/nodejs.webp',
    price: 'Rp 600.000',
    rating: '4.8',
    students: '4.155',
  },
  {
    name: 'Belajar Python Dasar',
    photo: '/src/assets/images/kelas/python.webp',
    price: 'Rp 450.000',
    rating: '4.7',
    students: '8.126',
  },
  {
    name: 'Belajar React JS',
    photo: '/src/assets/images/kelas/react.webp',
    price: 'Rp 550.000',
    rating: '4.9',
    students: '3.125',
  },
  {
    name: 'Belajar React Native',
    photo: '/src/assets/images/kelas/react.webp',
    price: 'Rp 500.000',
    rating: '4.7',
    students: '2.125',
  },
  {
    name: 'Belajar Vue JS',
    photo: '/src/assets/images/kelas/javascript.webp',
    price: 'Rp 500.000',
    rating: '4.7',
    students: '3.225',
  },
  {
    name: 'Belajar Bahasa Dart',
    photo: '/src/assets/images/kelas/flutter.webp',
    price: 'Rp 350.000',
    rating: '4.75',
    students: '2.225',
  },
  {
    name: 'Belajar Dart OOP',
    photo: '/src/assets/images/kelas/flutter.webp',
    price: 'Rp 375.000',
    rating: '4.65',
    students: '1.225',
  },
  {
    name: 'Belajar SASS',
    photo: '/src/assets/images/kelas/htmlcss.webp',
    price: 'Rp 275.000',
    rating: '4.85',
    students: '1.500',
  },
  {
    name: 'Belajar Django',
    photo: '/src/assets/images/kelas/python.webp',
    price: 'Rp 475.000',
    rating: '4.65',
    students: '1.600',
  },
  {
    name: 'Belajar Nest JS',
    photo: '/src/assets/images/kelas/javascript.webp',
    price: 'Rp 475.000',
    rating: '4.75',
    students: '1.300',
  },
  {
    name: 'Belajar MySQL',
    photo: '/src/assets/images/kelas/javascript.webp',
    price: 'Rp 250.000',
    rating: '4.75',
    students: '2.300',
  },
  {
    name: 'Belajar Mongo DB',
    photo: '/src/assets/images/kelas/javascript.webp',
    price: 'Rp 225.000',
    rating: '4.75',
    students: '2.300',
  },
]
export default katalogKelas
